spring:
    profiles:
        active: mysql
    datasource:
        url: jdbc:mysql://localhost:3306/dogdating?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
        username: webuser
        password: aSecretPass
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        database: mysql
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
    main:
        log-startup-info: false